"use client";
import { useCallback,useEffect,useState } from "react";
import { AlertTriangle } from "lucide-react";
import { ParkingResponseSchema,type ParkingLot } from "@/lib/parking/schema";
import { sortParkingLots } from "@/lib/parking/status";
import { ParkingCard } from "./parking-card";
import { ParkingSummary } from "./parking-summary";
type ViewState={kind:"loading"}|{kind:"error"}|{kind:"ready";lots:ParkingLot[]};
export function ParkingDashboard(){ const[state,setState]=useState<ViewState>({kind:"loading"}); const[refreshing,setRefreshing]=useState(false); const[announcement,setAnnouncement]=useState(""); const load=useCallback(async(isRefresh=false)=>{ if(isRefresh)setRefreshing(true); try{ const response=await fetch("/api/parking",{cache:"no-store"}); if(!response.ok)throw new Error("Request failed"); const parsed=ParkingResponseSchema.parse(await response.json()); setState({kind:"ready",lots:sortParkingLots(parsed.lots)}); if(isRefresh)setAnnouncement("Parking availability refreshed"); }catch{ setState({kind:"error"}); }finally{ setRefreshing(false); } },[]); useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]); if(state.kind==="loading")return <section aria-label="Checking parking availability"><p className="section-heading">Checking parking availability…</p><div className="parking-list"><div className="skeleton"/><div className="skeleton"/></div></section>; if(state.kind==="error")return <section className="state-card" role="alert"><div><span className="state-icon"><AlertTriangle aria-hidden="true"/></span><h2>Could not load parking data</h2><p>Check your connection and try again.</p><button className="retry-button" onClick={()=>void load()}>Try again</button></div></section>; if(state.lots.length===0)return <section className="state-card"><p>No parking areas are configured.</p></section>; return <><ParkingSummary bestLot={state.lots[0]} refreshing={refreshing} onRefresh={()=>void load(true)}/><div className="section-heading"><h2>All parking areas</h2><p>{state.lots.reduce((sum,lot)=>sum+lot.availableSpaces,0)} spaces across campus</p></div><section className="parking-list" aria-label="Parking areas">{state.lots.map((lot,index)=><ParkingCard key={lot.id} lot={lot} index={index}/>)}</section><p className="sr-only" aria-live="polite">{announcement}</p></>; }
